todo-mvc-lv/config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'

end

todo-mvc-lv/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo-mvc-lv/app/models/list.rb
class List < ApplicationRecord
end

todo-mvc-lv/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todo-mvc-lv/app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all
    # render 'list/index.html.erb'
    # raise @lists.inspect #was the controller able to get the lists
  end

  def show
    # params has all the data passed by a user
    # lists/:id - reading from URL
    @list = List.find(params[:id])
  end

  def create
    raise params.inspect
  end


end

todo-mvc-lv/app/helpers/application_helper.rb
module ApplicationHelper
end

todo-mvc-lv/app/helpers/lists_helper.rb
module ListsHelper
end

todo-mvc-lv/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvcLv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

todo-mvc-lv/app/views/lists/index.html.erb
<section class="todoapp">
	<header class="header">
		<h1>Your Lists</h1>
    <form>
      <%= form_for(@list) do |f|%>
        <%=f.text_field :name%>
      <%end%>
    </form>
	</header>

	<section class="main">
		<ul class="todo-list">
      <%@lists.each do |list|%>
        <li>
          <div class="view">
            <label><%=link_to list.name, list_path(list)%></a></label>
          </div>
        </li>
      <%end%>
    </ul>
  </section>

  <footer class="footer">
	</footer>
</section>

todo-mvc-lv/app/views/lists/show.html.erb
<section class="todoapp">
	<header class="header">
		<h1><%=@list.name%></h1>
		<input class="new-todo" placeholder="Add an item" autofocus="">
	</header>

	<section class="main">
		<ul class="todo-list">
        <li>
          <div class="view">
            <label>Milk</label>
          </div>
        </li>
        <li>
          <div class="view">
            <label>Cookies</label>
          </div>
        </li>
    </ul>
  </section>

  <footer class="footer">
	</footer>
</section>